name: Build docker images on release

on:
  release:
    types: [created]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    # environment: environment_name # use if you want to use a specific environment on repository level
    steps:
      - uses: actions/checkout@v3
        name: Checkout main repo
      - uses: docker/login-action@v2
        name: Log in to the Container registry
        with:
          registry: ${{ secrets.DOCKER_LOGIN_SERVER}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx
        id: buildx
      - uses: docker/build-push-action@v4
        name: Build and push Docker image
        with:
          context: .
          file: Dockerfile
          cache-from: type=registry,ref=${{ secrets.DOCKER_LOGIN_SERVER }}/${{ github.event.repository.name }}:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_LOGIN_SERVER }}/${{ github.event.repository.name }}:cache,mode=max
          push: true
          tags: ${{ secrets.DOCKER_LOGIN_SERVER }}/${{ github.event.repository.name }}:${{ github.event.release.tag_name }}
